// expo-env.d.ts is generated by `expo start` and git-ignored, so a fresh clone or CI running `tsc`
// would miss Expo's global types (CSS imports, EXPO_PUBLIC_* variables). This keeps them in reach.
/// <reference types="expo/types" />
